version: '3'
services:
  productoverview:
    build: ./
    restart: always
    depends_on:
      - 'database'
    ports:
      - '3001:3001'

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust

